title: 'parkha-na.github.io'
description: "A jekyll theme inspired by linux consoles for hackers, developers and script kiddies."
baseurl: 
url: "https://parkha-na.github.io"
future: true

header_pages:
  - index.md
  - about.md

style: dark

footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console

plugins:
  - jekyll-last-modified-at

# Optional. The default date format, used if none is specified in the tag.

